### PR TITLE
deps: use remark-vdom

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Closes GH-2

@wooorm tests appear to be failing, am I using `remark` / `remark-vdom` incorrectly?

### CODE REVIEW

**Comment by wooorm** [comment]
Checking!

**Comment by wooorm** [comment]
Ah yes, the thing is, remark-vdom exposes the virtual tree as an array (because markdown can have multiple nodes in the root, and virtual-dom doesn’t support something like DOM fragments).

Meaning, you’ll have to either:
- Wrap in a tag, e.g., a `<div>`;
- Wrap in a `<div></div>` and strip the starting and closing tags before returning to the user;
- I’m not very familiar with virtual widgets, maybe those could enable something like fragments?

**Comment by yoshuawuyts** [comment]
We're close now. I did the following:

``` js
  const tree = h('div', virtualMarkdown('# hello world'))
```

which correctly parses the array. Only there's now a new bug, which _I think_ is in `remark` / `remark-vdom`:

``` tap
# should return a virtual-dom tree
not ok 3 rendered html
  ---
    operator: equal
    expected: '<div><h1>hello world</h1></div>'
    actual:   '<div><h1>hello world</h1>\n</div>'
    at: Test.<anonymous> (/Users/yw/src/yw/virtual-markdown/test.js:18:5)
  ...
```

I don't think the extra newline should be there, right?

**Comment by yoshuawuyts** [comment]
Yup, just confirmed. It's not the `vdom-to-html` package that causes this.

**Comment by wooorm** [comment]
Maybe not, but the reason that the [newline](https://github.com/wooorm/remark-vdom/blob/6b4153986d59934e64fd87f344bb7afc376ff136/lib/compilers.js#L390-L392) is there is because of unix files (valid documents need have a final end-of-file end-of-line).

Arguable, virtual-dom’s are never written to files though....

**Comment by yoshuawuyts** [comment]
Yeah, I don't think it makes sense for in-memory structures; it's doing something rather unexpected now. Is that something that can easily be changed?

**Comment by wooorm** [comment]
Hmm. ok, I’ll remove it.

**Comment by yoshuawuyts** [comment]
All should be good; this is breaking change tho, so publishing as `v2.0.0`. Thanks heaps!

**Comment by wooorm** [comment]
Definitely! :ok_hand:

**Pull request closed without merging**
